# Lecture 07: Mathematical operations in Python: NumPy


#### Comparison of List and NumPy array

In [18]:
list_1=[1,2,3,4,5,6]
list_2=[8,45,6,7,8,9]

list_add= list_1+list_2
print(list_add)

#list_sub= list_2-list_1 not pssible , but possible for set
#print(list_sub)


#list_mul= list_1*list_2 not possible, also division
#print(list_mul)

[1, 2, 3, 4, 5, 6, 8, 45, 6, 7, 8, 9]


In [19]:
set(list_2)-set(list_1)

{7, 8, 9, 45}

In [20]:
#numpy, pandas, matplotlib, scikit-learn, seaborn
import numpy as np

In [21]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9])
arr_2 = np.array([1,-2,3,-4,5,-6,7,-8,9])

print(type(arr_1))
print(type(arr_2))
print(arr_2.dtype)

arr_add = arr_1 + arr_2
print("addition of two array = ", arr_add)
print(type(arr_add))

# arr_add = np.add(arr_3, arr_4)
# print(arr_add)

arr_sub = arr_1 - arr_2
print("subtraction of two array = ", arr_sub)

# arr_sub = np.subtract(arr_3, arr_4)
# print(arr_sub)

arr_mul = arr_1 * arr_2
print("multiplication of two array = ", arr_mul)

# arr_mul = np.multiply(arr_3, arr_4)
# print(arr_mul)

arr_div = arr_1 / arr_2
print("division of two array = ", arr_div)

# arr_div = np.divide(arr_5, arr_6)
# print(arr_div)

arr_mod = np.mod(arr_1, arr_2)
print("remainder after dividing two arrays = ", arr_mod)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64
addition of two array =  [ 2  0  6  0 10  0 14  0 18]
<class 'numpy.ndarray'>
subtraction of two array =  [ 0  4  0  8  0 12  0 16  0]
multiplication of two array =  [  1  -4   9 -16  25 -36  49 -64  81]
division of two array =  [ 1. -1.  1. -1.  1. -1.  1. -1.  1.]
remainder after dividing two arrays =  [0 0 0 0 0 0 0 0 0]


In [22]:
#pip install numpy

import numpy as np
arr_1=np.array(list_1)
arr_2=np.array(list_2)

print(arr_1)
print(arr_2)

arr_add=arr_1+arr_2
print(arr_add)

arr_sub=arr_1-arr_2
print(arr_sub)

arr_mul=arr_1*arr_2
print(arr_mul)

arr_div=arr_1/arr_2
print(arr_div)


[1 2 3 4 5 6]
[ 8 45  6  7  8  9]
[ 9 47  9 11 13 15]
[ -7 -43  -3  -3  -3  -3]
[ 8 90 18 28 40 54]
[0.125      0.04444444 0.5        0.57142857 0.625      0.66666667]


In [23]:
import numpy as np

arr_3= np.array([1,2])

#cannot +=*/ if dimention not same

In [24]:
import numpy as np

arr_4= np.array([[1,2,3],
                [4,5,6]])

arr_5=np.array([[1,2,3],
                [4,5,6]])
arr_add2=arr_4+arr_5

#arr_add2=np.add(arr_4+arr_5)
print(arr_add2)

arr_sub2=np.subtract(arr_4,arr_5)
print(arr_sub2)
arr_mul2=np.multiply(arr_4,arr_5)
print(arr_mul2)
print(arr_4.shape)
print(type(arr_4))



#matrix multiplication

#np.matmul

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
(2, 3)
<class 'numpy.ndarray'>


In [25]:
arr_6=np.array([2.6,34,5.2,7,8,9,5,7,8])
arr_7=np.array([2,34,5,7,8,9,5,7,8])
arr_8=np.array([2,34,5,7,8,9,5,7,8])

arr_pow=np.power(arr_6,arr_7)
print(arr_pow)

arr_sqr=np.square(arr_6)
print(arr_sqr)

arr_sqr=np.square(arr_6)
print(arr_sqr)

arr_abs=np.abs(arr_6)
print(arr_abs)

arr_ceil=np.ceil(arr_6) #ceiling
print(arr_ceil)

arr_floor=np.floor(arr_6)
print(arr_floor)

arr_round=np.round(arr_6)
print(arr_round)

[6.76000000e+00 1.17566389e+52 3.80204032e+03 8.23543000e+05
 1.67772160e+07 3.87420489e+08 3.12500000e+03 8.23543000e+05
 1.67772160e+07]
[   6.76 1156.     27.04   49.     64.     81.     25.     49.     64.  ]
[   6.76 1156.     27.04   49.     64.     81.     25.     49.     64.  ]
[ 2.6 34.   5.2  7.   8.   9.   5.   7.   8. ]
[ 3. 34.  6.  7.  8.  9.  5.  7.  8.]
[ 2. 34.  5.  7.  8.  9.  5.  7.  8.]
[ 3. 34.  5.  7.  8.  9.  5.  7.  8.]


#### array sum

In [26]:
arr_6=np.array([2.6,34,5.2,7,8,9,5,7,8])
arr_7=np.array([2,34,5,7,8,9,5,7,8])

arr_sum=np.sum([arr_6,arr_7])
print(arr_sum)

col_sum=np.sum([arr_6,arr_7], axis=0)
print(col_sum)

row_sum=np.sum([arr_6,arr_7], axis=1)
print(row_sum)

170.8
[ 4.6 68.  10.2 14.  16.  18.  10.  14.  16. ]
[85.8 85. ]


#### array product

In [27]:
arr_6=np.array([2,34,5.2,7,8,9,5,7,8])
arr_7=np.array([2,34,5,7,8,9,5,7,8])

arr_prod=np.prod([arr_6,arr_7])
print(arr_prod)

col_prod=np.prod([arr_6,arr_7],axis=0)
print(col_prod)

row_prod=np.prod([arr_6,arr_7],axis=1)
print(row_prod)

2394243455385600.5
[   4. 1156.   26.   49.   64.   81.   25.   49.   64.]
[49900032.00000001 47980800.        ]


#### Creating new matrix

In [28]:
identity_matrix = np.eye(3)
print(identity_matrix)

identity_ones = np.ones((3,3))
print(identity_ones)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Matrix operation

In [29]:
id_mat= np.eye(3)
print(id_mat)

one_matrix=np.ones((3,3))
print(one_matrix)

arr_matmul=np.matmul(id_mat,one_matrix)
print(arr_matmul)

arr_diag=np.diag(id_mat)
print(arr_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1.]


#### Array indexing and slicing

In [30]:
arr_1=np.array([2,34,5.2,7,8,9,5,7,8])

print(arr_1[-5:-1])
# print(arr_3[0])
# print(arr_3[1])
# print(arr_3[0,0])
# print(arr_3[0,1])
# print(arr_3[0,2])
# print(arr_3[1,0])
# print(arr_3[1,1])
# print(arr_3[1,2])

# print(arr_3[0,-1])
# print(arr_3[0,-2])
# print(arr_3[0,-3])

# print(arr_3[1:])

[8. 9. 5. 7.]


In [31]:
arr_4=np.array([[1,2,3],[4,5,6]])

print(arr_4[:,1:])

[[2 3]
 [5 6]]


#### numpy array filtering

In [32]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

find_four = np.where(arr == 4)
find_even = np.where(arr%2 == 0)
find_odd = np.where(arr%2 == 1)

print("index of value 4 : ", find_four)
print("index of the even numbers in the array : ", find_even)
print("index of the odd numbers in the array : ", find_odd)

index of value 4 :  (array([3, 5, 6]),)
index of the even numbers in the array :  (array([1, 3, 5, 6]),)
index of the odd numbers in the array :  (array([0, 2, 4]),)


In [33]:
find = arr[arr >= 4]

print(arr >= 4)
print(find)


[False False False  True  True  True  True]
[4 5 4 4]
